version: '3'
services:
  web:
    build: .
    ports:
    - "4005:4000"
    command: mix phoenix.server
    tty: true
    stdin_open: true
    volumes:
    - ./app:/app
    links:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432"
