version: '2'
services:
  web:
    build: .
    ports:
    - "4000:4000"
    command: mix phoenix.server
    volumes:
    - ./app:/app
    links:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432"
