version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
    - "4000:4000"
    command: mix phoenix.server
    tty: true
    stdin_open: true
    volumes:
    - ./backend/app:/app
    links:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    volumes:
      - /app/node_modules
      - ./frontend/app:/app
    command: 'npm start'
